export const COA = [
  // ASET LANCAR
  { code: "1.1.1.01", name: "Kas Tunai", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.1.02", name: "Kas di Bank Mandiri", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.1.03", name: "Kas di Bank BJB", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.1.04", name: "Kas di Bank BNI", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.1.05", name: "Kas di Bank BCA", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.2.01", name: "Piutang Usaha", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.2.03", name: "Piutang Simpanan Pokok Anggota", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.2.04", name: "Piutang Simpanan Wajib Anggota", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.2.05", name: "Uang Muka Pembelian", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.3.01", name: "Penyisihan Piutang Usaha Tak Tertagih", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.1.3.02", name: "Penyisihan Piutang Simpanan Pokok Anggota Tak Tertagih", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.1.3.03", name: "Penyisihan Piutang Simpanan Wajib Anggota Tak Tertagih", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.1.4.01", name: "Persediaan Barang Dagang", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.4.02", name: "Persediaan.....", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.4.03", name: "Persediaan.....", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.4.04", name: "Persediaan.....", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.4.05", name: "Persediaan.....", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.4.06", name: "Persediaan.....", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.4.07", name: "Perlengkapan", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.5.01", name: "Sewa Dibayar Dimuka", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.5.02", name: "PPh 25", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.5.03", name: "PPN Masukan", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.8.99", name: "Aset Lancar Lainnya", normal_balance: "Debit", type: "ASSET" },
  { code: "1.1.9.01", name: "RK Pusat", normal_balance: "Debit", type: "ASSET" },
  // ASET TIDAK LANCAR
  { code: "1.2.1.01", name: "Investasi dalam Deposito", normal_balance: "Debit", type: "ASSET" },
  { code: "1.2.1.99", name: "Investasi Lainnya", normal_balance: "Debit", type: "ASSET" },
  { code: "1.3.1.01", name: "Tanah", normal_balance: "Debit", type: "ASSET" },
  { code: "1.3.2.01", name: "Gedung dan Bangunan", normal_balance: "Debit", type: "ASSET" },
  { code: "1.3.3.01", name: "Peralatan dan Meubelair", normal_balance: "Debit", type: "ASSET" },
  { code: "1.3.4.01", name: "Kendaraan", normal_balance: "Debit", type: "ASSET" },
  { code: "1.3.5.01", name: "Akumulasi Penyusutan Gedung dan Bangunan", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.3.5.02", name: "Akumulasi Penyusutan Peralatan dan Meubelair", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.3.5.03", name: "Akumulasi Penyusutan Kendaraan", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.3.9.99", name: "Aset Tetap Lainnya", normal_balance: "Debit", type: "ASSET" },
  { code: "1.4.1.01", name: "Aplikasi My KLMP Mekarjaya", normal_balance: "Debit", type: "ASSET" },
  { code: "1.4.2.01", name: "Amortisasi Aset Tidak Berwujud", normal_balance: "Kredit", type: "ASSET" },
  { code: "1.5.1.01", name: "Investasi Jangka Panjang", normal_balance: "Debit", type: "ASSET" },
  { code: "1.9.1.99", name: "Aset Lain-lain lainnya", normal_balance: "Debit", type: "ASSET" },
  // KEWAJIBAN
  { code: "2.1.1.01", name: "Utang Simpanan Pokok", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.1.02", name: "Utang Simpanan Wajib", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.1.03", name: "Utang Simpanan Sukarela", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.2.01", name: "Utang SHU", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.3.01", name: "Utang Usaha", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.4.01", name: "PPN Keluaran", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.4.02", name: "PPh 21", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.4.03", name: "PPh 23", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.4.04", name: "PPh 29", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.5.01", name: "Utang Gaji dan Tunjangan", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.6.01", name: "Utang Listrik", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.6.02", name: "Utang Telepon", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.6.99", name: "Utang Utilitas Lainnya", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.7.01", name: "Pendapatan Sewa Diterima Dimuka", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.8.01", name: "Utang kepada Pihak Ketiga Jk. Pendek", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.8.99", name: "Utang kepada Pihak Ketiga Jk. Pendek Lainnya", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.9.01", name: "Utang Kepada Anggota - E Wallet", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.1.9.99", name: "Utang Jangka Pendek Lainnya", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.2.1.01", name: "Utang kepada Pihak Ketiga Jk. Panjang", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.2.2.01", name: "Utang Ke Bank", normal_balance: "Kredit", type: "LIABILITY" },
  { code: "2.2.9.99", name: "Utang Jangka Panjang Lainnya", normal_balance: "Kredit", type: "LIABILITY" },
  // EKUITAS
  { code: "3.1.1.01", name: "Simpanan Pokok", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.1.2.01", name: "Simpanan Wajib", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.1.3.01", name: "Simpanan Sukarela", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.1.3.02", name: "Penyertaan Anggota", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.2.1.01", name: "Hibah Dari Pemerintah", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.3.1.01", name: "Cadangan", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.4.1.01", name: "Sisa Hasil Usaha Belum Dibagikan", normal_balance: "Kredit", type: "EQUITY" },
  { code: "3.9.1.01", name: "Ikhtisar Sisa Hasil Usaha", normal_balance: "Kredit", type: "EQUITY" },
  // PENDAPATAN
  { code: "4.1.1.01", name: "Pendapatan Penjualan Toko", normal_balance: "Kredit", type: "REVENUE" },
  { code: "4.1.1.02", name: "Pendapatan Layanan Digital", normal_balance: "Kredit", type: "REVENUE" },
  { code: "4.1.1.03", name: "Pendapatan Non-Usaha", normal_balance: "Kredit", type: "REVENUE" },
  { code: "4.1.1.04", name: "Pendapatan Hibah", normal_balance: "Kredit", type: "REVENUE" },
  { code: '4.1.1.99', name: 'Potongan Penjualan (Promo)', type: 'REVENUE', normal_balance: 'Debit' },
  { code: '4.1.2.01', name: 'Pendapatan Jasa Pinjaman', type: 'REVENUE', normal_balance: 'Kredit' },
  // HPP
  { code: "5.1.1.01", name: "Harga Pokok Penjualan Toko", normal_balance: "Debit", type: "COGS" },
  { code: "5.1.1.02", name: "Harga Pokok Penjualan Layanan Digital", normal_balance: "Debit", type: "COGS" },
  { code: "5.1.2.01", name: "Pembelian", normal_balance: "Debit", type: "COGS" },
  // BEBAN OPERASIONAL
  { code: "6.1.1.01", name: "Beban Gaji dan Tunjangan Pegawai", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.1.03", name: "Beban Honor Lembur", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.1.04", name: "Beban Insentif (Bonus)", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.1.05", name: "Beban Komisi", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.1.06", name: "Beban Seragam Pegawai", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.1.07", name: "Beban Penguatan SDM", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.1.99", name: "Beban Pegawai Lainnya", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.2.01", name: "Beban ATK", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.2.02", name: "Beban Foto Copy", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.2.03", name: "Beban Konsumsi Rapat", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.2.04", name: "Beban Cetak dan Dekorasi", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.2.99", name: "Beban Perlengkapan Lainnya", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.3.01", name: "Beban Pemeliharaan dan Perbaikan", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.4.01", name: "Beban Listrik", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.4.02", name: "Beban Telepon dan Internet", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.4.03", name: "Beban Aplikasi", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.4.99", name: "Beban Utilitas Lainnya", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.5.01", name: "Beban Sewa", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.5.02", name: "Beban Asuransi", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.6.01", name: "Beban Keamanan", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.6.02", name: "Beban Kebersihan", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.7.01", name: "Beban Penyisihan Piutang Tak Tertagih", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.8.02", name: "Beban Penyusutan Gedung dan Bangunan", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.8.03", name: "Beban Penyusutan Peralatan dan Meubelair", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.8.04", name: "Beban Penyusutan Kendaraan", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.8.05", name: "Beban Amortisasi Aset Tak Berwujud", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.01", name: "Beban Parkir", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.02", name: "Beban Ongkos Kirim", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.03", name: "Beban Pendamping", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.04", name: "Beban Pengawas", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.05", name: "Beban Audit", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.06", name: "Beban Perjalanan Dinas", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.07", name: "Beban Transportasi", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.08", name: "Beban Jamuan Tamu", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.1.9.99", name: "Beban Lainnya", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.2.2.01", name: "Beban Administrasi dan Umum Lainnya", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.2.2.02", name: "Beban Promosi", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.2.2.03", name: "Beban Dana Sosial", normal_balance: "Debit", type: "EXPENSE" },
  { code: "6.2.3.99", name: "Beban Pemasaran Lainnya", normal_balance: "Debit", type: "EXPENSE" },
  { code: '6.9.9.99', name: 'Beban Selisih Stok (Opname)', normal_balance: 'Debit', type: 'EXPENSE' },
  // PENDAPATAN LAINNYA
  { code: "9.1.1.01", name: "Pendapatan Bunga", normal_balance: "Kredit", type: "OTHER_REVENUE" },
  { code: "9.1.2.01", name: "Pendapatan Bantuan/Sumbangan/Hibah", normal_balance: "Kredit", type: "OTHER_REVENUE" },
  { code: "9.1.3.01", name: "Pendapatan Denda", normal_balance: "Kredit", type: "OTHER_REVENUE" },
  { code: "9.1.9.99", name: "Pendapatan Lain-lain (Surplus Stok)", normal_balance: "Kredit", type: "OTHER_REVENUE" },
  // BEBAN LAINNYA & PAJAK
  { code: "9.2.1.01", name: "Beban Administrasi Bank", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.2.2.01", name: "Beban Bunga", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.2.3.01", name: "Beban Denda", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.2.9.99", name: "Beban Lain-lain lainnya", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.01", name: "Beban Pajak Bunga Bank", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.02", name: "Beban Pajak Reklame", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.03", name: "Beban PPh 21", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.04", name: "Beban PPh 23", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.05", name: "Beban PPh 25", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.06", name: "Beban PPh 29", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.07", name: "Beban PPh Final", normal_balance: "Debit", type: "OTHER_EXPENSE" },
  { code: "9.3.1.99", name: "Beban Pajak Lainnya", normal_balance: "Debit", type: "OTHER_EXPENSE" },
];

export const getAccountsByType = (...types) => COA.filter(a => types.includes(a.type));